create_checkin:
  pattern: /checkins
  defaults: { _controller: Controller\CheckIns::create }
  requirements: { _method: POST }

get_checkin:
  pattern: /checkins/{id}
  defaults: { _controller: Controller\CheckIns::show}
  requirements: { _method: GET}

update_checkin:
  pattern: /checkins/{id}
  defaults: { _controller: Controller\CheckIns::update}
  requirements: { _method: PUT}

delete_checkin:
  pattern: /checkins/{id}
  defaults: { _controller: Controller\CheckIns::delete}
  requirements: { _method: DELETE}

get_by_venue:
  pattern: /checkins/venue/{venue}
  defaults: { _controller: Controller\CheckIns::getByVenue}
  requirements: { _method: GET}

get_by_venue_type:
  pattern: /checkins/venue_type/{venue_type}
  defaults: { _controller: Controller\CheckIns::getByVenueType}
  requirements: { _method: GET}