
create_circle:
  pattern: /me/circles
  defaults: { _controller: Controller\User::addCircle}
  requirements: { _method: POST}

get_circles:
  pattern: /me/circles
  defaults: { _controller: Controller\User::getCircles}
  requirements: { _method: GET}

get_circle_detail:
  pattern: /me/circles/{id}
  defaults: { _controller: Controller\User::getCircleDetail}
  requirements: { _method: GET}

update_circle:
  pattern: /me/circles/{id}
  defaults: { _controller: Controller\User::updateCustomCircle}
  requirements: { _method: PUT}

remove_friend:
  pattern: /me/circles/{id}/remove
  defaults: { _controller: Controller\User::removeFriendFromCircle}
  requirements: { _method: PUT}

delete_circle:
  pattern: /me/circles/{id}
  defaults: { _controller: Controller\User::deleteCustomCircle}
  requirements: { _method: DELETE}

remove_friend:
  pattern: /me/circles/{id}/rename
  defaults: { _controller: Controller\User::renameCustomCircle}
  requirements: { _method: PUT}

add_friend_to_multiple_circle:
  pattern: /me/circles/friend/{id}
  defaults: { _controller: Controller\User::addFriendToMultipleCircle}
  requirements: { _method: PUT}


