create_message:
  pattern: /messages/
  defaults: { _controller: Controller\Messages::create }
  requirements: { _method: POST }

create_message_thread:
  pattern: /messages/thread
  defaults: { _controller: Controller\Messages::createOrGetMessageThread }
  requirements: { _method: POST }

sent_messages:
  pattern: /messages/sent
  defaults: { _controller: Controller\Messages::getByCurrentUser }
  requirements: { _method: GET }

inbox_messages:
  pattern: /messages/inbox
  defaults: { _controller: Controller\Messages::getInbox }
  requirements: { _method: GET }

status_message:
  pattern: /messages/{id}/status/{status}
  defaults: { _controller: Controller\Messages::updateStatus }
  requirements:
    _method: POST|PUT
    status: read|unread

update_recipient_to_message:
  pattern: /messages/{id}/recipients
  defaults: { _controller: Controller\Messages::updateRecipients }
  requirements:
    _method: POST|PUT

replies_since_message:
  pattern: /messages/{id}/replies
  defaults: { _controller: Controller\Messages::getRepliesByLastVisitedSince }
  requirements:
    _method: GET

get_unread_message_by_id:
  pattern: /messages/{id}/unread
  defaults: { _controller: Controller\Messages::getUnreadMessagesById }
  requirements: { _method: GET }

delete_message:
  pattern:  /messages/{id}
  defaults: { _controller: Controller\Messages::delete }
  requirements: { _method: DELETE }

read_message:
  pattern: /messages/{id}
  defaults: { _controller: Controller\Messages::getById }
  requirements: { _method: GET }

add_recipient_to_message:
  pattern: /messages/{id}/recipients/add
  defaults: { _controller: Controller\Messages::addRecipients }
  requirements:
    _method: POST|PUT


