my_newsfeed:
  pattern: /me/newsfeed
  defaults: { _controller: Controller\UserActivities::getActivities, type: json }
  requirements: { _method: GET }

my_network_newsfeed_html:
  pattern: /me/network/newsfeed.html
  defaults: { _controller: Controller\UserActivities::getActivities, type: html }
  requirements: { _method: GET }


my_newsfeed_html:
  pattern: /me/newsfeed.html
  defaults: { _controller: Controller\UserActivities::getActivities, type: html }
  requirements: { _method: GET }

user_newsfeed:
  pattern: /{userId}/newsfeed
  defaults: { _controller: Controller\UserActivities::getActivitiesByUserId, type: json }
  requirements: { _method: GET }

user_newsfeed_html:
  pattern: /{userId}/newsfeed.html
  defaults: { _controller: Controller\UserActivities::getActivitiesByUserId, type: html }
  requirements: { _method: GET }

like_a_feed:
  pattern: /newsfeed/{id}/like
  defaults: { _controller: Controller\UserActivities::likeById, type: json }
  requirements: { _method: PUT }
