user_all_notofications:
  pattern: /request/notification
  defaults: { _controller: Controller\User::getUserNotifications}
  requirements: { _method: GET}

update_user_notofications:
  pattern: /me/notification/{notificationId}
  defaults: { _controller: Controller\User::updateNotification}

user_notofications:
  pattern: /me/notifications
  defaults: { _controller: Controller\User::getNotifications}
  requirements: { _method: GET}

user_notoficationscount:
  pattern: /me/notificationscount
  defaults: { _controller: Controller\User::getNotificationsCount}
  requirements: { _method: GET}