

create_review:
  pattern: /reviews
  defaults: { _controller: Controller\Reviews::create }
  requirements: { _method: POST }

get_review:
  pattern: /reviews/{id}
  defaults: { _controller: Controller\Reviews::show}
  requirements: { _method: GET}

update_review:
  pattern: /reviews/{id}
  defaults: { _controller: Controller\Reviews::update}
  requirements: { _method: PUT}

delete_review:
  pattern: /reviews/{id}
  defaults: { _controller: Controller\Reviews::delete}
  requirements: { _method: DELETE}

get_by_venue:
  pattern: /reviews/venue/{venue}
  defaults: { _controller: Controller\Reviews::getByVenue}
  requirements: { _method: GET}

get_by_venue_type:
  pattern: /reviews/venue_type/{venue_type}
  defaults: { _controller: Controller\Reviews::getByVenueType}
  requirements: { _method: GET}