#!/usr/bin/env php
<?php
require_once __DIR__ . '/../app/autoload.php';
// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/AppBootstrap.php';
require_once __DIR__.'/AppKernel.php';

require_once __DIR__ . '/../src/Commands/Greet.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

use Worker\Greet;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = !$input->hasParameterOption(array('--no-debug', ''));

//$kernel = new AppKernel($env, $debug);
$application = new Application();

$application->add(new Greet);

$application->run();
