web:
  root: http://192.168.1.71/social_maps/web

mongodb:
  host: 'localhost'
  port: 27017
  database: 'socialmaps'

imagetype:
  thumb:
    width: 50
    height: 50

  medium:
    width: 150
    height: 150

  large:
    width: 250
    height: 250