web:
  root: http://203.76.126.69/social_maps/web

mongodb:
  host: 'localhost'
  port: 27017
  database: 'socialmaps_staged'

logging:
  # DEBUG, WARN, ERROR
  level: "DEBUG"
  file: "%s/logs/web_%s.log"

imagetype:
  thumb:
    width: 50
    height: 50

  medium:
    width: 150
    height: 150

  large:
    width: 250
    height: 250