web:
  root: http://203.76.126.69/stage_social_maps/web

mongodb:
  host: 'localhost'
  port: 27017
  database: 'socialmaps'

logging:
  # DEBUG, WARN, ERROR
  level: "DEBUG"
  file: "%s/logs/web_%s.log"