web:
  root: http://203.76.126.69/social_maps/web

mongodb:
  host: '127.0.0.1'
  port: 27017
  database: 'socialmaps'

gearman:
  host: '127.0.0.1'
  port: 4730

swiftmailer:
  transport:  smtp
  encryption: ssl
  auth_mode:  login
  host:       smtp.gmail.com
  port:       587
  username:   test@socialmaps.com
  password:   123456

facebook:
  appId: 197770310286117
  secret: d31a93b130c927645f8f1a97d2bd66e9

googlePlace:
  apiKey: AIzaSyD_R73_cR92W83gUHkiqw35-yO4erVYsaw