web:
  root: http://192.168.1.212:8888

mongodb:
  host: 'localhost'
  port: 27017
  database: 'socialmaps_staged'

logging:
  # DEBUG, WARN, ERROR
  level: "DEBUG"
  file: "%s/logs/web_%s.log"

imagetype:
  thumb:
    width: 135
    height: 135

  medium:
    width: 570
    height: 370

  large:
    width: 640
    height: 920
